const setting = {
    type: 'chat-gpt',
    gptCookies: [
        {
            name: '__cf_bm',
            value:'',
            domain: '.chat.openai.com',
            path: '/',
            expires: 1695042828,
            size: 35,
            httpOnly: true,
            secure: true,
            session: false,
            sameSite: 'None',
            sameParty: false,
            sourceScheme: 'Secure',
            sourcePort: 443
        },
        {
            name: '__stripe_mid',
            value:'',
            domain: '.chat.openai.com',
            path: '/',
            expires: 1695042828,
            size: 35,
            httpOnly: false,
            secure: true,
            session: false,
            sameSite: 'strict',
            sameParty: false,
            sourceScheme: 'Secure',
            sourcePort: 443
        },
        {
            name: '__stripe_sid',
            value:'',
            domain: '.chat.openai.com',
            path: '/',
            expires: 1695042828,
            size: 35,
            httpOnly: false,
            secure: true,
            session: false,
            sameSite: 'strict',
            sameParty: false,
            sourceScheme: 'Secure',
            sourcePort: 443
        },
        {
            name: '_cfuvid',
            value:'',
            domain: '.chat.openai.com',
            path: '/',
            expires: 1695042828,
            size: 35,
            httpOnly: true,
            secure: true,
            session: true,
            sameSite: 'None',
            sameParty: false,
            sourceScheme: 'Secure',
            sourcePort: 443
        },
        {
            name: 'cf_clearance',
            value:'',
            domain: '.chat.openai.com',
            path: '/',
            expires: 1695042828,
            size: 35,
            httpOnly: true,
            secure: true,
            session: false,
            sameSite: 'None',
            sameParty: false,
            sourceScheme: 'Secure',
            sourcePort: 443
        },
        {
            name: 'auth0',
            value:'',
            domain: '.auth0.openai.com',
            path: '/',
            expires: 1695042828,
            size: 35,
            httpOnly: true,
            secure: true,
            session: false,
            sameSite: 'None',
            sameParty: false,
            sourceScheme: 'Secure',
            sourcePort: 443
        },
        {
            name: 'auth0_compat',
            value:'',
            domain: '.auth0.openai.com',
            path: '/',
            expires: 1695042828,
            size: 35,
            httpOnly: true,
            secure: true,
            session: false,
            sameSite: 'None',
            sameParty: false,
            sourceScheme: 'Secure',
            sourcePort: 443
        },
        {
            name: 'did',
            value:'',
            domain: '.auth0.openai.com',
            path: '/',
            expires: 1695042828,
            size: 35,
            httpOnly: true,
            secure: true,
            session: false,
            sameSite: 'None',
            sameParty: false,
            sourceScheme: 'Secure',
            sourcePort: 443
        },
        {
            name: 'did_compat',
            value:'',
            domain: '.auth0.openai.com',
            path: '/',
            expires: 1695042828,
            size: 35,
            httpOnly: true,
            secure: true,
            session: false,
            sameSite: 'None',
            sameParty: false,
            sourceScheme: 'Secure',
            sourcePort: 443
        },
        {
            name: '__Host-next-auth.csrf-token',
            value:'',
            domain: 'chat.openai.com',
            path: '/',
            expires: 1695042828,
            size: 35,
            httpOnly: true,
            secure: true,
            session: true,
            sameSite: 'None',
            sameParty: false,
            sourceScheme: 'Secure',
            sourcePort: 443
        },
        {
            name: '__Secure-next-auth.callback-url',
            value:'',
            domain: 'chat.openai.com',
            path: '/',
            expires: 1695042828,
            size: 35,
            httpOnly: true,
            secure: true,
            session: true,
            sameSite: 'None',
            sameParty: false,
            sourceScheme: 'Secure',
            sourcePort: 443
        },
        {
            name: '__Secure-next-auth.session-token',
            value:'',
            domain: 'chat.openai.com',
            path: '/',
            expires: 1695042828,
            size: 35,
            httpOnly: true,
            secure: true,
            session: true,
            sameSite: 'None',
            sameParty: false,
            sourceScheme: 'Secure',
            sourcePort: 443
        },
        {
            name: '_dd_s',
            value:'',
            domain: 'chat.openai.com',
            path: '/',
            expires: 1695042828,
            size: 35,
            httpOnly: true,
            secure: true,
            session: true,
            sameSite: 'None',
            sameParty: false,
            sourceScheme: 'Secure',
            sourcePort: 443
        },
        {
            name: '_uasid',
            value:'',
            domain: 'chat.openai.com',
            path: '/',
            expires: 1695042828,
            size: 35,
            httpOnly: true,
            secure: true,
            session: true,
            sameSite: 'None',
            sameParty: false,
            sourceScheme: 'Secure',
            sourcePort: 443
        }
    ],
    XCookie : {
        name: 'auth_token',
        value:'',
        domain: '.twitter.com',
        path: '/',
        expires: 1695042828,
        size: 35,
        httpOnly: true,
        secure: true,
        session: false,
        sameSite: 'None',
        sameParty: false,
        sourceScheme: 'Secure',
        sourcePort: 443
    },
    gptPrompt:'your_prompt'
}

module.exports = setting;